services:
  web:
    build: .
    container_name: monitoring-web
    ports:
      - '3000:3000'
      - '5555:5555' # used in dev for prisma studio
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@monitoring-db:5432/monitoring
      - NODE_ENV=deployment
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: monitoring-db
    environment:
      POSTGRES_DB: monitoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d monitoring']
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
